name: 🐳 Multi Architecture Test

on:
  workflow_dispatch:
  
jobs:
  build:
    name: 🐳 Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
            
      - id: determine-version
        name: Determine Semantic Versions
        uses: gittools/actions/gitversion/execute@v0
       
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into docker.io
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./configuration-visualization/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dekoeky/configuration-visualization:test